### ISSUE TITLE
Adding _self_ to rearangment.yaml

### ISSUE THREAD

**Issue by rimvydasrub** [peterdavidfagan/mujoco_robot_environments#9]
When running the package, you experience the following warning:

```bash
UserWarning: In 'rearrangement': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
```
which could be in principle to solved by modifying ``mujoco_robot_environments/config/rearrangment.yaml`` file to something like this:

```yaml
# mujoco simulation parameters
physics_dt: 0.001
control_dt: 0.005
gravity: [0.0, 0.0, -9.8]
nconmax: 1000
njmax: 2000
offheight: 640
offwidth: 640
znear: 0.0005
viewer: False # whether or not to use passive viewer

# weights and biases experiment tracking
wandb:
  use: True
  experiment_name: rearrangement_transporter
  tags: ["original transporter network"]
  notes: "Curently debugging."
  track_gradients: False
  resume: False
  resume_run:
    id: xxxxx # not currently being used
    load_epoch: 1
  
  metrics:
    pick_loss:
      step_metric: epoch
      summary: min
  
  tables:
    data_table:
      columns: ["placeholder"]

simulation_tuning_mode: False

defaults:
  - __self__ # additional line
  - arena: rearrangement_table
  - robots: franka_robotiq_2f85
  - task: rearrangement
  - dataset: default
```
Would it be possible to extend or that would create unexpected behaviours in the codebase?
